const actions = {

    NAMESPACE_CHANGE: 'NAMESPACE_CHANGE',
    NAMESPACE_CHANGED: 'NAMESPACE_CHANGED',

    INSTANCES_LOAD: 'INSTANCES_LOAD',
    INSTANCES_LOADED: 'INSTANCES_LOADED',

    NAMESPACES_LOAD: 'NAMESPACES_LOAD',
    NAMESPACES_LOADED: 'NAMESPACES_LOADED',

    USER_SIGN_UP: 'USER_SIGNUP',
    USER_SIGNED_UP: 'USER_SIGNED_UP',

    USER_LOGIN: 'USER_LOGIN',
    USER_LOGGED: 'USER_LOGGED',

    USER_LOGOUT: 'USER_LOGOUT'
};

export default actions;
