const actions = {

    NAMESPACE_CHANGE: 'NAMESPACE_CHANGE',
    NAMESPACE_CHANGED: 'NAMESPACE_CHANGED',

    INSTANCES_SUBSCRIBE: 'INSTANCES_SUBSCRIBE',
    INSTANCES_SUBSCRIBED: 'INSTANCES_SUBSCRIBED',
    INSTANCES_UPDATE: 'INSTANCES_UPDATE',

    NAMESPACES_LOAD: 'NAMESPACES_LOAD',
    NAMESPACES_LOADED: 'NAMESPACES_LOADED',

    USER_SIGN_UP: 'USER_SIGNUP',
    USER_LOGIN: 'USER_LOGIN',
    USER_LOGGED: 'USER_LOGGED',

    USER_LOGOUT: 'USER_LOGOUT',

    SESSION_DESTROY: 'SESSION_DESTROY',
    SESSION_DESTROYED: 'SESSION_DESTROYED',
    SESSION_TOKEN_STORE: 'SESSION_TOKEN_STORE',
    SESSION_TOKEN_STORED: 'SESSION_TOKEN_STORED'

};

export default actions;
