const sessionKeys = {
    ACTIVE_NAMESPACE: 'ACTIVE_NAMESPACE',
    EXPANDED_INSTANCES: 'EXPANDED_INSTANCES',
    EXPANDED_ADMIN_INSTANCES: 'EXPANDED_ADMIN_INSTANCES',
    SESSION_TOKEN: 'SESSION_TOKEN'
};

export default sessionKeys;
