FROM python:2.7.11

ENV ELASTICKUBE_PATH    /opt/elastickube
ENV PYTHONPATH          /opt/elastickube

WORKDIR ${ELASTICKUBE_PATH}

ADD data ${ELASTICKUBE_PATH}/data
ADD api  ${ELASTICKUBE_PATH}/api

RUN pip install --no-compile tornado motor PyJWT pycurl cairosvg

CMD while true; do (python api/server.py; sleep 5) done
